apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: auth-service
data:
  NODE_ENV: "development"
  PORT: "5000"
  APP_RUNTIME_MODE: "production"
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  KAFKA_ENABLED: "true"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "authentication-service"
  KAFKA_AUTH_TOPIC: "auth.events"
  MONGODB_URL: "mongodb://mongodb-service:27017"
  MONGODB_DB_NAME: "authentication_service"
  MONGODB_AUDIT_COLLECTION: "auth_audit_logs"
  TWO_FA_EXPIRES_SECONDS: "300"
  ADMIN_EMAILS: "admin@test.ts"
